controller_list:
  - name: robot_flo_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1_flo
      - joint_2_flo
      - joint_3_flo
      - joint_4_flo
      - joint_5_flo
      - joint_6_flo
  - name: robot_simon_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1_simon
      - joint_2_simon
      - joint_3_simon
      - joint_4_simon
      - joint_5_simon
      - joint_6_simon
  - name: turn_table_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_turn_table